### ISSUE TITLE
Recent update 0.1.51 fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by mikestp27** [Eugeny/ajenti-v#279]
Running `apt-get update` on Ubuntu 14.04 system fails with the following messages:
```
dpkg-deb: error: archive '/var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/ajenti-v-nginx_0.1.51_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by Eugeny** [comment]
Fixed

**Comment by mikestp27** [comment]
Package ajenti-v-nginx 0.1.52 does not seem to be available yet... 
http://realrepo.ajenti.org:8888/debian/

**Comment by Eugeny** [comment]
Try again now

**Comment by mikestp27** [comment]
I see the fix you have done and I understand it should work... but it doesn't...
Running `apt-get update` still fails...

```
Get:1 http://repo.ajenti.org/ng/debian/ main/main ajenti-v-nginx all 0.1.52 [5,072 B]
Fetched 5,072 B in 0s (14.6 kB/s)   
dpkg-deb: error: archive '/var/cache/apt/archives/ajenti-v-nginx_0.1.52_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/ajenti-v-nginx_0.1.52_all.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by mikestp27** [comment]
Works fine with latest version  `ajenti-v-nginx 0.1.52`.
Thank you!
